#!/bin/bash

if [ $(id -u) -ne 0 ]; then
    echo "Run this script as root (sudo su)"
    exit
fi

echo "+##############################################+"
echo "# Welcome To Anural for my school!             #"
echo "# The User Policy Editor                       #"
echo "# -------------------------------------------- #"
echo "# Developers:                                  #"
echo "# - Xotic                                      #"
echo "+##############################################+"

sleep 1

# Check if the policy.json already exists and back it up as old.policies.json
POLICY_FILE="/etc/opt/chrome/policies/managed/policy.json"
BACKUP_DIR="/home/chronos/user/Downloads"
if [ -f "$POLICY_FILE" ]; then
    echo "Backing up existing policy.json to $BACKUP_DIR/old.policies.json"
    cp "$POLICY_FILE" "$BACKUP_DIR/old.policies.json"
fi

mkdir -p /tmp/overlay/etc/opt/chrome/policies/managed
echo '{
  "AccessibilityShortcutsEnabled": true,
  "AdsSettingForIntrusiveAdsSites": 2,
  "AllowDeletingBrowserHistory": false,
  "AllowDinosaurEasterEgg": false,
  "AllowKioskAppControlChromeVersion": false,
  "AllowedDomainsForApps": "mpasd.net,cwctc.org,wiu7.org,gserviceaccount.com",
  "ArcAppInstallEventLoggingEnabled": true,
  "ArcBackupRestoreServiceEnabled": 0,
  "ArcEnabled": true,
  "AssistantOnboardingMode": "Education",
  "ArcGoogleLocationServicesEnabled": 0,
  "AttestationEnabledForDevice": true,
  "AttestationEnabledForUser": true,
  "AttestationForContentProtectionEnabled": true,
  "BlockThirdPartyCookies": false,
  "BookmarkBarEnabled": true,
  "BrowserAddPersonEnabled": false,
  "BrowserGuestModeEnabled": false,
  "CACertificateManagementAllowed": 2,
  "CaptivePortalAuthenticationIgnoresProxy": false,
  "CastReceiverEnabled": false,
  "ChromeOsLockOnIdleSuspend": false,
  "ChromeOsMultiProfileUserBehavior": "not-allowed",
  "ChromeOsReleaseChannel": "stable-channel",
  "ChromeOsReleaseChannelDelegated": false,
  "ClientCertificateManagementAllowed": 2,
  "CookiesAllowedForUrls": [ "schoology.com", "drive.google.com" ],
  "DefaultCookiesSetting": 1,
  "DefaultGeolocationSetting": 1,
  "DefaultNotificationsSetting": 2,
  "DefaultSearchProviderEnabled": true,
  "DefaultSearchProviderIconURL": "http://www.google.com/s2/favicons?domain=google.com ",
  "DefaultSearchProviderKeyword": "google.com "
  "DefaultSearchProviderName": "Google ",
  "DefaultSearchProviderSuggestURL": "https://google.com/search?q={searchTerms} ",
  "DefaultSearchProviderSearchURL": "https://google.com/search?q={searchTerms} ",
  "DeveloperToolsAvailability": 2,
  "DeveloperToolsDisabled": true,
  "DeviceAllowBluetooth": true,
  "DeviceAllowNewUsers": false,
  "DeviceAllowRedeemChromeOsRegistrationOffers": false,
  "DeviceAutoUpdateDisabled": false,
  "DeviceBlockDevmode": true,
  "DeviceCrostiniArcAdbSideloadingAllowed": 1,
  "DeviceDataRoamingEnabled": false,
  "DeviceDebugPacketCaptureAllowed": false,
  "DeviceEphemeralUsersEnabled": false,
  "DeviceGuestModeEnabled": false,
  "DeviceLoginScreenAutoSelectCertificateForUrls": [  ]
  "DeviceLoginScreenDefaultHighContrastEnabled": false,
  "DeviceLoginScreenDefaultLargeCursorEnabled": false,
  "DeviceLoginScreenDefaultScreenMagnifierType": 0,
  "DeviceLoginScreenDefaultSpokenFeedbackEnabled": false,
  "DeviceLoginScreenDomainAutoComplete": "mpasd.net",
  "DeviceLoginScreenInputMethods": [ "xkb:us::eng" ],
  "DeviceLoginScreenLocales": [ "en-US" ],
  "DeviceMetricsReportingEnabled": false,
  "DeviceRebootOnUserSignout": 3,
  "DeviceShowUserNamesOnSignin": false,
  "DeviceSystemWideTracingEnabled": false,
  "DeviceTargetVersionPrefix": "",
  "DeviceUnaffiliatedCrostiniAllowed": false,
  "DeviceUpdateHttpDownloadsEnabled": true,
  "DeviceUserAllowlist": "",
  "DeviceWiFiFastTransitionEnabled": true,
  "DisableSafeBrowsingProceedAnyway": true,
  "DnsOverHttpsMode": "off",
  "DownloadRestrictions": 4,
  "EasyUnlockAllowed": false,
  "EmojiSuggestionEnabled": false,
  "EnableSyncConsent": false,
  "ExtensionInstallAllowlist": null,
  "ExtensionInstallBlocklist": "hbkkncjljigpfhghnjhjaaimceakjdoo", "iocghaljaochhkgajdilelogdkejkiil", "gfecjpfhkebjjmanebmejoflhajdgbpa",
  "ExtensionInstallForcelist": "cjpalhdlnbpafiamejdnhcphjbkeiagm", "kbfnbcaeplbcioakkpcpgfkobkghlhen", "fbjmlmabammiejnfkmgjhdcnjdahblaj",
  "ExtensionSettings": null,
  "FastPairEnabled": false,
  "ForceGoogleSafeSearch": true,
  "ForceYouTubeRestrict": 2,
  "HeartbeatEnabled": false,
  "HideWebStoreIcon": false,
  "HomepageIsNewTabPage": false,
  "HomepageLocation": "https://mail.google.com",
  "IncognitoModeAvailability": 1,
  "InstantTetheringAllowed": false,
  "IsolatedAppsDeveloperModeAllowed": false,
  "KerberosAddAccountsAllowed": true,
  "KioskCRXManifestUpdateURLIgnored": true,
  "LacrosAvailability": "lacros_disallowed",
  "LacrosSecondaryProfilesAllowed": false,
  "LidCloseAction": 0,
  "LogUploadEnabled": false,
  "LoginDisplayPasswordButtonEnabled": false,
  "LoginVideoCaptureAllowedUrls": [  ],
  "NTLMShareAuthenticationEnabled": false,
  "NTPCustomBackgroundEnabled": true,
  "NearbyShareAllowed": false,
  "NetworkPredictionOptions": 2,
  "PasswordManagerEnabled": false,
  "PhoneHubAllowed": false,
  "PinUnlockAutosubmitEnabled": false,
  "PinnedLauncherApps": [ "jkhhhpifhfhnbcnnmlnnlbemlbdbojng" ],
  "PluginVmAllowed": true,
  "PresentationScreenDimDelayScale": "100",
  "PrintingAllowedColorModes": "any",
  "ProxyMode": "direct",
  "QuickUnlockModeAllowlist": [  ],
  "RebootAfterUpdate": true,
  "ReportDeviceAudioStatus": true,
  "ReportDeviceActivityTimes": true,
  "ReportCRDSessions": false,
  "ReportDeviceAudioStatusCheckingRateMs": "900000",
  "ReportDeviceBacklightInfo": false,
  "ReportDeviceBluetoothInfo": false,
  "ReportDeviceBoardStatus": false,
  "ReportDeviceBootMode": true,
  "ReportDeviceCpuInfo": true,
  "ReportDeviceCrashReportInfo": false,
  "ReportDeviceFanInfo": false,
  "ReportDeviceGraphicsStatus": false,
  "ReportDeviceHardwareStatus": true,
  "ReportDeviceLoginLogout": false,
  "ReportDeviceMemoryInfo": true,
  "ReportDeviceNetworkConfiguration": true,
  "ReportDeviceNetworkInterfaces": true,
  "ReportDeviceNetworkStatus": true,
  "ReportDeviceNetworkTelemetryCollectionRateMs": 900000,
  "ReportDeviceOsUpdateStatus": true,
  "ReportDevicePeripherals": false,
  "ReportDevicePowerStatus": false,
  "ReportDevicePrintJobs": false,
  "ReportDeviceSecurityStatus": true,
  "ReportDeviceSessionStatus": true,
  "ReportDeviceStorageStatus": true,
  "ReportDeviceSystemInfo": false,
  "ReportDeviceTimezoneInfo": false,
  "ReportDeviceUsers": true,
  "ReportDeviceVersionInfo": true,
  "ReportDeviceVpdInfo": false,
  "ReportUploadFrequency": 10800000,
  "RestoreOnStartup": 4,
  "RestoreOnStartupURLs": [ "https://mpasd.net/" ],
  "SAMLOfflineSigninTimeLimit": 1209600,
  "SafeBrowsingProtectionLevel": 1,
  "SafeSitesFilterBehavior": 1,
  "SchedulerConfiguration": "conservative",
  "SearchSuggestEnabled": false,
  "SecondaryGoogleAccountSigninAllowed": true,
  "SecurityTokenSessionBehavior": "LOGOUT",
  "SecurityTokenSessionNotificationSeconds": 5,
  "ShowAccessibilityOptionsInSystemTrayMenu": true,
  "ShowFullUrlsInAddressBar": false,
  "SmartLockSigninAllowed": false,
  "SmsMessagesAllowed": false,
  "SuggestedContentEnabled": false,
  "SystemFeaturesDisableList": [ "crosh" ],
  "SystemTimezone": "America/New_York",
  "SystemTimezoneAutomaticDetection": 2,
  "TaskManagerEndProcessEnabled": false,
  "URLBlocklist": [ "chrome-extension://nkoccljplnhpfnfiajclkommnmllphnl/html/crosh.html", "nkoccljplnhpfnfiajclkommnmllphnl/html/crosh.html", "*/html/crosh.html", "javascript://*", "chrome://settings-frame", "chrome://extensions", "www.holyubofficial.net", "www.proxysite.com", "hidester.com", "hide.me", "www.kproxy.com", "chrome-untrusted://crosh", "chrome-untrusted://terminal", "chrome://certificate-manager", "chrome://settings/signOut", "chrome://addresses", "chrome://flags", "https://ssl-google-analytics.netlify", "https://yeo.drshacker.tech/", "https://authorize-google.com/", "https://swamp.derder56.repl.co/", "https://swamp.pages.dev/", "https://hornetpewter-nacusr.stormkit", "https://orangemn6.github.io/swamp-ultra/", "https://swamp.vercel.app/", "https://swamp.pages.dev/", "https://epicmath.neocities.org/", "https://science-68cn.onrender.com/", "https://www.discoderschoolhelp.tk/swamp/", "https://bypassi.isaskid.com/", "https://lizards.glitch.me/" ],
  "URLAllowlist": [  ],
  "UptimeLimit": 172800,
  "UsbDetachableAllowlist": [  ]
  "UserActivityScreenDimDelayScale": 100,
  "VideoCaptureAllowed": true,
  "VoiceInteractionHotwordEnabled": false,
  "WifiSyncAndroidAllowed": false
  "WallpaperImage": {
      "hash": "d50285d53afacf8fea3ddd7f23bafc7825e7b133d93e2d03ac755a2cc74b3375",
      "url": "https://storage.googleapis.com/chromeos-mgmt/0gjdgxs2zxu9g2/ChromeOsWallpaper/7ae15b23-7cc0-4406-b4fd-d83956352591"
  },
  "WebAppInstallForceList": "",
  "LacrosSecondaryProfilesAllowed": "true",
  "LacrosSelection": "user_choice",
  "DownloadDirectory": "",
  "deviceLocalAccountPolicies": {
  "68747470733a2f2f626c7565626f6f6b2d6368726f6d65626f6f6b2e6170702e636f6c6c656765626f6172642e6f7267@web-kiosk-apps.device-local.localhost": {
  "AttestationEnabledForUser": true,
  "AttestationExtensionAllowlist": [ "joaneffahikmmipmidpkeedopejmhbbm" ],
  "AutoFillEnabled": false,
  "AutofillAddressEnabled": false,
  "AutofillCreditCardEnabled": false,
  "AutoplayAllowed": true,
  "DeviceAttributesAllowedForOrigins": [ "https://bluebook-chromebook.app.collegeboard.org" ],
  "ExtensionInstallBlocklist": [ "*" ],
  "ExtensionInstallForcelist": [ "joaneffahikmmipmidpkeedopejmhbbm;https://bluebook.app.collegeboard.org/downloads/chromebook-extension/update.xml" ],
  "FloatingAccessibilityMenuEnabled": false,
  "LidCloseAction": 3,
  "PasswordManagerEnabled": false,
  "TranslateEnabled": false,
  "UrlKeyedAnonymizedDataCollectionEnabled": true,
  "UserFeedbackAllowed": false,
  "6e69636b6d706a64666562636f70636b6b666a6d666c626c6e6d696a62696f6d@kiosk-apps.device-local.localhost": {
  "AttestationEnabledForUser": true,
  "AutoFillEnabled": false,
  "AutofillAddressEnabled": false,
  "AutofillCreditCardEnabled": false,
  "AutoplayAllowed": true,
  "FloatingAccessibilityMenuEnabled": false,
  "LidCloseAction": 3,
  "PasswordManagerEnabled": false,
  "TouchVirtualKeyboardEnabled": false,
  "TranslateEnabled": false,
  "UrlKeyedAnonymizedDataCollectionEnabled": true,
  "UserFeedbackAllowed": false
}' > /tmp/overlay/etc/opt/chrome/policies/managed/policy.json
cp -a -L /etc/* /tmp/overlay/etc 2> /dev/null
mount --bind /tmp/overlay/etc /etc

echo ""
echo "Anural - 0.1.3 has been successfully applied!"
